In [2]:
import numpy as np

from numpy.testing import assert_allclose

# Part I. Construct a Householder reflection of a vector.

Given a vector $\mathbf{x}$, and a plane with a normal vector $\mathbf{u}$, the Householder transformation reflects $\mathbf{x}$ about the plane.

The matrix of the Householder transformation is

$$
\mathbf{H} = \mathbf{1} - 2 \mathbf{u} \mathbf{u}^T
$$

Given two equal-length vectors $\mathbf{x}$ and $\mathbf{y}$, a rotation which brings $\mathbf{x}$ to $\mathbf{y}$ is a Householder transform with

$$
\mathbf{u} = \frac{\mathbf{x} - \mathbf{y}}{||\mathbf{x} - \mathbf{y}||}
$$

In [29]:
def householder(vec):
    """Construct a Householder reflection to zero out 2nd and further components of a vector.

    Parameters
    ----------
    vec : array-like of floats, shape (n,)
        Input vector
    
    Returns
    -------
    outvec : array of floats, shape (n,)
        Transformed vector, with ``outvec[1:]==0`` and ``|outvec| == |vec|``
    H : array of floats, shape (n, n)
        Orthogonal matrix of the Householder reflection
    """
    vec = np.asarray(vec, dtype=float)
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)
    
    # ENTER YOUR CODE HERE
#     H = 1 - 2uu^T
    outvec = np.zeros(vec.shape)
    outvec[0] = np.linalg.norm(vec)
    u = (vec - outvec)/np.linalg.norm(vec - outvec)
    u = u.reshape(u.shape[0], 1)
    H = np.identity(u.shape[0]) - 2*np.dot(u,np.transpose(u))
    return (outvec, H)

In [30]:
# Test (marked)

v = np.array([1, 2, 3])
v1, h = householder(v)

assert_allclose(np.dot(h, v1), v)
# assert_allclose(np.dot(h, v), v1)

In [31]:
rndm = np.random.RandomState(1234)

vec = rndm.uniform(size=7)
v1, h = householder(vec)

assert_allclose(np.dot(h, v1), vec)

# Part II. Compute the QR decomposition of a matrix.

Given a rectangular $m\times n$ matrix $\mathbf{A}$, construct a Householder reflector matrix $\mathbf{H}_1$ which transforms the first column of $\mathbf{A}$ (and call the result $\mathbf{A}^{(1)}$)

$$
\mathbf{H}_1 \mathbf{A} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
&& \dots&& \\
0      & \times & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(1)}\;.
$$

Now consider the lower-right submatrix of $\mathbf{A}^{(1)}$, and construct a Householder reflector which annihilates the second column of $\mathbf{A}$:

$$
\mathbf{H}_2 \mathbf{A}^{(1)} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & 0      & \times & \dots & \times \\
&& \dots&& \\
0      & 0      & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(2)} \;.
$$

Repeating the process $n-1$ times, we obtain

$$
\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} = \mathbf{R} \;,
$$

with $\mathbf{R}$ an upper triangular matrix. Since each $\mathbf{H}_k$ is orthogonal, so is their product. The inverse of an orthogonal matrix is orthogonal. Hence the process generates the $QR$ decomposition of $\mathbf{A}$. 

In [104]:
def qr_decomp(a):
    """Compute the QR decomposition of a matrix.
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    
    Returns
    -------
    q : ndarray, shape(m, m)
        The orthogonal matrix
    r : ndarray, shape(m, n)
        The upper triangular matrix
        
    Examples
    --------
    >>> a = np.random.random(size=(3, 5))
    >>> q, r = qr_decomp(a)
    >>> np.assert_allclose(np.dot(q, r), a)
    
    """
    a1 = np.array(a, copy=True, dtype=float)
    m, n = a1.shape
    
    # ENTER YOUR CODE HERE
    H = []
    for i in range(n):
        col = a1[i:, i]
        new_col, H_i = householder(col)
        H_i = np.pad(H_i, (i, 0), 'constant')
        for j in range(i):
            H_i[j][j] = 1
        H.append(H_i)
        a1 = np.dot(H_i, a1)
    r = a1
    q = np.transpose(H[0])
    for k in range(1, len(H)):
        q = np.dot(q, np.transpose(H[k]))
    return (q, r)

In [105]:
# Might want to turn this on for prettier printing: zeros instead of `1e-16` etc

np.set_printoptions(suppress=True)

In [106]:
# Test (marked)

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
q, r = qr_decomp(a)

# test that Q is indeed orthogonal
assert_allclose(np.dot(q, q.T), np.eye(5), atol=1e-10)

# test the decomposition itself
assert_allclose(np.dot(q, r), a)

In [107]:
a

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261],
       [0.27646426, 0.80187218, 0.95813935],
       [0.87593263, 0.35781727, 0.50099513],
       [0.68346294, 0.71270203, 0.37025075]])

In [108]:
np.dot(q, r)

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261],
       [0.27646426, 0.80187218, 0.95813935],
       [0.87593263, 0.35781727, 0.50099513],
       [0.68346294, 0.71270203, 0.37025075]])

In [109]:
q, r

(array([[ 0.13665049,  0.53601299, -0.09369752,  0.7697136 ,  0.30459557],
        [ 0.56035895,  0.0935397 , -0.53326881,  0.01839528, -0.62652547],
        [ 0.19725922,  0.65948912,  0.60068463, -0.32384673, -0.24589462],
        [ 0.62498418, -0.50418303,  0.52144688,  0.28453698,  0.04822969],
        [ 0.48765568,  0.12171264, -0.27224305, -0.47049398,  0.67223293]]),
 array([[ 1.40152769,  1.2514379 ,  0.89523615],
        [ 0.        ,  0.84158252,  0.68447942],
        [-0.        , -0.        ,  0.5496046 ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        , -0.        , -0.        ]]))

Now compare your decompositions to the library function (which actually wraps the corresponding LAPACK functions)

In [110]:
from scipy.linalg import qr
qq, rr = qr(a)

assert_allclose(np.dot(qq, rr), a)

In [111]:
qq, rr

(array([[-0.13665049,  0.53601299,  0.09369752,  0.661619  , -0.49749149],
        [-0.56035895,  0.0935397 ,  0.53326881, -0.52477245, -0.34276292],
        [-0.19725922,  0.65948912, -0.60068463, -0.37879015,  0.14784752],
        [-0.62498418, -0.50418303, -0.52144688,  0.18967657, -0.21750907],
        [-0.48765568,  0.12171264,  0.27224305,  0.32774225,  0.75222783]]),
 array([[-1.40152769, -1.2514379 , -0.89523615],
        [ 0.        ,  0.84158252,  0.68447942],
        [ 0.        ,  0.        , -0.5496046 ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]]))

Check if your `q` and `r` agree with `qq` and `rr`. Explain.

The difference is in signs, but this difference is compensated by matrix multiplication 

*Enter your explanation here (Russian or English, up to you)*

# Part III. Avoid forming Householder matrices explicitly.

Note the special structure of the Householder matrices: A reflector $\mathbf{H}$ is completely specified by a reflection vector $\mathbf{u}$. Also note that the computational cost of applying a reflector to a matrix strongly depends on the order of operations:

$$
\left( \mathbf{u} \mathbf{u}^T \right) \mathbf{A}  \qquad \textrm{is } O(m^2 n)\;,
$$
while
$$
\mathbf{u} \left( \mathbf{u}^T \mathbf{A} \right) \qquad \textrm{is } O(mn)
$$

Thus, it seems to make sense to *avoid* forming the $\mathbf{H}$ matrices. Instead, one stores the reflection vectors, $\mathbf{u}$, themselves, and provides a way of multiplying an arbitrary matrix by $\mathbf{Q}^T$, e.g., as a standalone function (or a class).

Write a function which constructs the `QR` decomposition of a matrix *without ever forming the* $\mathbf{H}$ matrices, and returns the $\mathbf{R}$ matrix and reflection vectors. Write a second function, which uses the reflection vertices to multiply a matrix with $\mathbf{Q}^T$. Make sure to include enough comments for a marker to follow your implementation, and add tests.

In [135]:
def decomposition(a):
    a1 = np.array(a, copy=True, dtype=float)
    m, n = a1.shape
    U = []
    for i in range(n):
        a2 = np.array(a1[i:, i:], copy = True, dtype = float)
        x = a2[:, 0]
        y = np.zeros(x.shape)
        y[0] = np.linalg.norm(x)
        u = (x - y)/np.linalg.norm(x - y)
        u = u.reshape(u.shape[0], 1)
        a1[i:, i:] = a1[i:, i:] - 2*np.dot(u, np.dot(np.transpose(u), a1[i:,i:]))
        u = np.insert(u, 0, np.zeros(m - u.shape[0]))
        u = u.reshape(u.shape[0], 1)
        U.append(u)
    return U, a1

In [139]:
rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
u, r1 = decomposition(a)

In [149]:
# Проверка:
np.allclose(r1, r)

True

In [152]:
def multiplication(a, u):
    for i in u:
        a = a - 2 * np.dot(i, np.dot(np.transpose(i), a))
    return a

In [153]:
r2 = multiplication(a, u)

In [155]:
# Проверка:
np.allclose(r2, r1)

True